basePath: /apis
host: localhost:6476
info:
  contact: {}
  description: This is a Go Gin Graphql Hexagonal API server.
  title: Go Gin Graphql Hexagonal API
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - application/json
      description: do Hello
      produces:
      - application/json
      responses:
        "200":
          description: Hello
          schema:
            type: string
      summary: Hello example
      tags:
      - example
swagger: "2.0"
